// This file is automatically generated. Any changes may be lost.
// The following declarations describes all resources that might be loaded dynamically.

// Brush Aliases
Syntax.alias("clang", ["cpp", "c", "objective-c"]);
Syntax.alias("ruby", []);

// CSS Extensions
Syntax.styles["jquery.syntax.layout.table"] = "jquery.syntax.layout.table.css";
