// This file is automatically generated. Any changes may be lost.
// The following declarations describes all resources that might be loaded dynamically.

// Brush Aliases
Syntax.alias("applescript", []);
Syntax.alias("asm", []);
Syntax.alias("clang", ["cpp", "c++", "c", "objective-c"]);
Syntax.alias("css", []);
Syntax.alias("diff", ["patch"]);
Syntax.alias("html", ["xml"]);
Syntax.alias("javascript", ["js", "actionscript"]);
Syntax.alias("plain", ["text"]);
Syntax.alias("ruby", []);

// CSS Extensions
Syntax.styles["jquery.syntax.brush.applescript"] = "jquery.syntax.brush.applescript.css";
Syntax.styles["jquery.syntax.brush.asm"] = "jquery.syntax.brush.asm.css";
Syntax.styles["jquery.syntax.brush.clang"] = "jquery.syntax.brush.clang.css";
Syntax.styles["jquery.syntax.brush.css"] = "jquery.syntax.brush.css.css";
Syntax.styles["jquery.syntax.brush.diff"] = "jquery.syntax.brush.diff.css";
Syntax.styles["jquery.syntax.brush.html"] = "jquery.syntax.brush.html.css";
Syntax.styles["jquery.syntax.layout.table"] = "jquery.syntax.layout.table.css";
